/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PalestrasRouteImport } from './routes/palestras'
import { Route as DiagnosticoMaturidadeRouteImport } from './routes/diagnostico-maturidade'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseOraculoRouteImport } from './routes/case.oraculo'
import { Route as CaseNaturinVendasRouteImport } from './routes/case.naturin-vendas'
import { Route as CaseIaRhRouteImport } from './routes/case.ia-rh'
import { Route as CaseCopaMundoRouteImport } from './routes/case.copa-mundo'
import { Route as CaseChackappRouteImport } from './routes/case.chackapp'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'

const PalestrasRoute = PalestrasRouteImport.update({
  id: '/palestras',
  path: '/palestras',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoMaturidadeRoute = DiagnosticoMaturidadeRouteImport.update({
  id: '/diagnostico-maturidade',
  path: '/diagnostico-maturidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseOraculoRoute = CaseOraculoRouteImport.update({
  id: '/case/oraculo',
  path: '/case/oraculo',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseNaturinVendasRoute = CaseNaturinVendasRouteImport.update({
  id: '/case/naturin-vendas',
  path: '/case/naturin-vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseIaRhRoute = CaseIaRhRouteImport.update({
  id: '/case/ia-rh',
  path: '/case/ia-rh',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCopaMundoRoute = CaseCopaMundoRouteImport.update({
  id: '/case/copa-mundo',
  path: '/case/copa-mundo',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseChackappRoute = CaseChackappRouteImport.update({
  id: '/case/chackapp',
  path: '/case/chackapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRoute
  '/diagnostico-maturidade': typeof DiagnosticoMaturidadeRoute
  '/palestras': typeof PalestrasRoute
  '/case/chackapp': typeof CaseChackappRoute
  '/case/copa-mundo': typeof CaseCopaMundoRoute
  '/case/ia-rh': typeof CaseIaRhRoute
  '/case/naturin-vendas': typeof CaseNaturinVendasRoute
  '/case/oraculo': typeof CaseOraculoRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRoute
  '/diagnostico-maturidade': typeof DiagnosticoMaturidadeRoute
  '/palestras': typeof PalestrasRoute
  '/case/chackapp': typeof CaseChackappRoute
  '/case/copa-mundo': typeof CaseCopaMundoRoute
  '/case/ia-rh': typeof CaseIaRhRoute
  '/case/naturin-vendas': typeof CaseNaturinVendasRoute
  '/case/oraculo': typeof CaseOraculoRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRoute
  '/diagnostico-maturidade': typeof DiagnosticoMaturidadeRoute
  '/palestras': typeof PalestrasRoute
  '/case/chackapp': typeof CaseChackappRoute
  '/case/copa-mundo': typeof CaseCopaMundoRoute
  '/case/ia-rh': typeof CaseIaRhRoute
  '/case/naturin-vendas': typeof CaseNaturinVendasRoute
  '/case/oraculo': typeof CaseOraculoRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cases'
    | '/diagnostico-maturidade'
    | '/palestras'
    | '/case/chackapp'
    | '/case/copa-mundo'
    | '/case/ia-rh'
    | '/case/naturin-vendas'
    | '/case/oraculo'
    | '/admin/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cases'
    | '/diagnostico-maturidade'
    | '/palestras'
    | '/case/chackapp'
    | '/case/copa-mundo'
    | '/case/ia-rh'
    | '/case/naturin-vendas'
    | '/case/oraculo'
    | '/admin/leads'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cases'
    | '/diagnostico-maturidade'
    | '/palestras'
    | '/case/chackapp'
    | '/case/copa-mundo'
    | '/case/ia-rh'
    | '/case/naturin-vendas'
    | '/case/oraculo'
    | '/_authenticated/admin/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CasesRoute: typeof CasesRoute
  DiagnosticoMaturidadeRoute: typeof DiagnosticoMaturidadeRoute
  PalestrasRoute: typeof PalestrasRoute
  CaseChackappRoute: typeof CaseChackappRoute
  CaseCopaMundoRoute: typeof CaseCopaMundoRoute
  CaseIaRhRoute: typeof CaseIaRhRoute
  CaseNaturinVendasRoute: typeof CaseNaturinVendasRoute
  CaseOraculoRoute: typeof CaseOraculoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/palestras': {
      id: '/palestras'
      path: '/palestras'
      fullPath: '/palestras'
      preLoaderRoute: typeof PalestrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico-maturidade': {
      id: '/diagnostico-maturidade'
      path: '/diagnostico-maturidade'
      fullPath: '/diagnostico-maturidade'
      preLoaderRoute: typeof DiagnosticoMaturidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/oraculo': {
      id: '/case/oraculo'
      path: '/case/oraculo'
      fullPath: '/case/oraculo'
      preLoaderRoute: typeof CaseOraculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/naturin-vendas': {
      id: '/case/naturin-vendas'
      path: '/case/naturin-vendas'
      fullPath: '/case/naturin-vendas'
      preLoaderRoute: typeof CaseNaturinVendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/ia-rh': {
      id: '/case/ia-rh'
      path: '/case/ia-rh'
      fullPath: '/case/ia-rh'
      preLoaderRoute: typeof CaseIaRhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/copa-mundo': {
      id: '/case/copa-mundo'
      path: '/case/copa-mundo'
      fullPath: '/case/copa-mundo'
      preLoaderRoute: typeof CaseCopaMundoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/chackapp': {
      id: '/case/chackapp'
      path: '/case/chackapp'
      fullPath: '/case/chackapp'
      preLoaderRoute: typeof CaseChackappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CasesRoute: CasesRoute,
  DiagnosticoMaturidadeRoute: DiagnosticoMaturidadeRoute,
  PalestrasRoute: PalestrasRoute,
  CaseChackappRoute: CaseChackappRoute,
  CaseCopaMundoRoute: CaseCopaMundoRoute,
  CaseIaRhRoute: CaseIaRhRoute,
  CaseNaturinVendasRoute: CaseNaturinVendasRoute,
  CaseOraculoRoute: CaseOraculoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
